name: 💅 Lint

on:
    push:
        branches:
            - "main"
        paths:
            - '**.go'
            - '**.mod'
    pull_request:
        branches:
          - "main"
        paths:
            - '**.go'
            - '**.mod'
    workflow_dispatch:

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version:  '>=1.23'
                    cache: false
            -
                name: Code Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -
                name: golangci-lint
                uses: golangci/golangci-lint-action@v6
                with:
                    version: v1.62.2
                    args: --timeout 5m
                    working-directory: .